In [24]:
import pandas as pd
import Utilidades as ut

#Convierte el cvs en un df 
#encoding='latin', permite detectar carateres especiales para eliminarlos, no funciona con utf-8
df1 = pd.read_csv('Tuition_Assistance_20240525.csv', encoding='latin1')
dfing = pd.read_csv('Tuition_Assistance_20240525.csv', encoding='latin1')
#Regsitros vacios por columna
#df1.isnull().sum()

#Renombra las columnas
df1.columns = ["Departamento","Especialidad","Grado","Colegio","Nombre Curso","Descripcion Curso","Precio"]

#Elimina carateres de los campos
ut.elimaCarateres(df1,'Colegio')
ut.elimaCarateres(df1,'Nombre Curso')
ut.elimaCarateres(df1,'Descripcion Curso')

#Normalzia los espacios en blanco
ut.eliminaEspacios(df1)

#Coloca en mayuscula la primera letra de cada palabra (title) y quita los espacios al principio y al final (lstrip,rstrip)
ut.normalizaTexto(df1,'Departamento')
ut.normalizaTexto(df1,'Especialidad')
ut.normalizaTexto(df1,'Grado')
ut.normalizaTexto(df1,'Colegio')
ut.normalizaTexto(df1,'Nombre Curso')
ut.normalizaTexto(df1,'Descripcion Curso')

#Reemplaza los valores, cuando hayan coincidencias del valor en la columna 1, reemplaza en la columa 2
ut.actualizaValores(df1,'Colegio','Associa','Grado','Certificate')
ut.actualizaValores(df1,'Colegio','Associa','Especialidad','Other/Misc.')

ut.actualizaValores(df1,'Colegio','Society','Grado','Certificate')
ut.actualizaValores(df1,'Colegio','Society','Especialidad','Other/Misc.')

ut.actualizaValores(df1,'Colegio','Center','Grado','Certificate')
ut.actualizaValores(df1,'Colegio','Center','Especialidad','Other/Misc.')

#Reemplaza los valores Aa en el campo Grado por Associate of Arts
df1 = df1.replace({'Grado': 'Aa'} , 'Associate of Arts', regex=True)

#Reemplaza los valores Academi en el campo Colegio por Academy
df1 = df1.replace({'Colegio': 'Academi'} , 'Academy', regex=True)

#Reempleza valores en base a condiciones
Col = ['Alliance','Academy','Training','Institute','College','School']
for shcoll in Col:
    ut.actualizaValores2(df1,'Colegio',shcoll,'Grado','Associate of Arts',"'Associate of Arts','Bachelors (Ba/Bs)'")

ut.actualizaValores2(df1,'Colegio','College','Grado','Bachelors (Ba/Bs)',"'Associate of Arts','Bachelors (Ba/Bs)'")
ut.actualizaValores2(df1,'Colegio','University','Grado','Masters (Ma/Ms/Mph/Etc.)',"'Masters (Ma/Ms/Mph/Etc.)','Ph.D. (Dcs)','Ph.D. (Dde)','Juris Doctor'")

#Rellena los registros nulos de Especialidad con General Studies
df1['Especialidad'] = df1['Especialidad'].fillna('General Studies')

#Rellena los registros nulos de Descripcion Curso con el Nombre Curso
df1['Descripcion Curso'] = df1['Descripcion Curso'].fillna(df1['Nombre Curso'])

#Reemplaza los valores Non-Degree en el campo Grado con Other
df1 = df1.replace({'Grado': 'Non-Degree'} , 'Other', regex=True)

#Reemplaza los valores 0 en el campo Precio con 100
df1 = df1.replace({'Precio': 0} , 100, regex=True)

#Crea un df sin nulos en ningun campo, reinicia el indice y elimina la columna con el indice anterior
dfCln = df1.dropna().reset_index(drop=True)

#Cambio el precio de float a int
dfCln['Precio'] = dfCln['Precio'].astype(int)

#dfCln3 = dfCln.query('Colegio.str.contains("Association")', engine='python')
#dfCln.loc[dfCln['Colegio'].isin(dfCln3['Colegio']), 'Grado'] = 'Certificate'

#Crea un df con los nulos en cualequier campo, y reinicia el indice y elimina la columna con el indice anterior
dfNulls = dfing[dfing.isna().any(axis=1)].reset_index(drop=True)

#Crea un excel con 1 hoja por cada df
with pd.ExcelWriter('Limpieza1.xlsx') as writer:
    dfCln.to_excel(writer,sheet_name='LIMPIEZA')
    dfing.to_excel(writer,sheet_name='INGESTA')
    dfNulls.to_excel(writer,sheet_name='NULOS_INGESTA')

dfCln
#Ver registros especifico
#df1.iloc[3953]

,Departamento,Especialidad,Grado,Colegio,Nombre Curso,Descripcion Curso,Precio
0,Police,Business/Admin./Mgmt.,Associate of Arts,Montgomery College Rockville Campus,Introduction To Business,An Introductory Course Designed To Survey The ...,392
1,Police,Business/Admin./Mgmt.,Associate of Arts,Montgomery College Rockville Campus,Ma 160,A General Calculus Course Primarily For Busine...,392
2,Police,Business/Admin./Mgmt.,Associate of Arts,Montgomery College Rockville Campus,Intro To American Music,A Survey Of American Popular Music From The Tu...,392
3,Health & Human Services,Business/Admin./Mgmt.,Masters (Ma/Ms/Mph/Etc.),Bowie State University,Public Policy Analysis,Focus Is On The Analysis Of Costs And Benefits...,1062
4,Health & Human Services,Other/Misc.,Masters (Ma/Ms/Mph/Etc.),Mount St Mary'S University,Mha 500 Contemporary Issues In Health Care,"The Historical, Current, And Future Organizati...",1569
...,...,...,...,...,...,...,...
4363,Police,Political Science,Associate of Arts,Montgomery County Community College,Pol 101 American Goverment,"Structure, Powers, And Processes Of The Americ...",402
4364,Fire/Rescue Services,General Studies,Associate of Arts,Fire Department Training Network,Fireground Survival & Rit,Fire Combat,1200
4365,Liquor Control,Information Technology,Associate of Arts,Montgomery County Community College,Unix/Linux System Administration,These Are Saturday Classes.\n\nIntroduction To...,528
4366,Police,Other/Misc.,Other,Victory First,Rds Handgun Instructor,Rds Handgun Instructor For Leo Only,750
4367,Transportation,Civil And Environmental Engineering,Associate of Arts,Montgomery College Rockville Campus,Art 101- Introduction To Drawing,An Introduction To Drawing And Creative Visual...,336